version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: raincast
      POSTGRES_USER: raincast_user
      POSTGRES_PASSWORD: raincast123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: