# Generated by Django 5.2.5 on 2025-08-15 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("will_rain", models.BooleanField()),
                ("chance", models.PositiveSmallIntegerField()),
                ("precip_mm", models.FloatField(blank=True, null=True)),
                ("condition", models.CharField(blank=True, max_length=100)),
                (
                    "api_provider",
                    models.CharField(default="WeatherAPI", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
